// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaChatMVC.Models;

namespace PruebaChatMVC.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20210905045432_Migracion-Ultima")]
    partial class MigracionUltima
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaChatMVC.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pasword")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            id = new Guid("cc63eea7-2d0f-4508-93d5-7673d8a2bccc"),
                            Pasword = "123",
                            UserName = "Daniel"
                        });
                });

            modelBuilder.Entity("PruebaChatMVC.Models.UserChat", b =>
                {
                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("UsuarioChat");
                });

            modelBuilder.Entity("PruebaChatMVC.Models.UserChat", b =>
                {
                    b.HasOne("PruebaChatMVC.Models.User", "relChat_User")
                        .WithOne("relChat_User")
                        .HasForeignKey("PruebaChatMVC.Models.UserChat", "idUser")
                        .HasConstraintName("Relacion_Usuario_Chat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("relChat_User");
                });

            modelBuilder.Entity("PruebaChatMVC.Models.User", b =>
                {
                    b.Navigation("relChat_User");
                });
#pragma warning restore 612, 618
        }
    }
}
