// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PruebaChatMVC.Models;

namespace PruebaChatMVC.Migrations
{
    [DbContext(typeof(Model))]
    [Migration("20210905223231_Hola mundo")]
    partial class Holamundo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PruebaChatMVC.Models.MessageSended", b =>
                {
                    b.Property<Guid>("idMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaDeEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensjae")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Reciber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Sender")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("idMensaje");

                    b.HasIndex("Reciber");

                    b.HasIndex("Sender");

                    b.ToTable("MensajesEnviados");
                });

            modelBuilder.Entity("PruebaChatMVC.Models.User", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pasword")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("id");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            id = new Guid("4d5c3e8d-68a2-480f-80ef-a21bb46a2105"),
                            Pasword = "123",
                            UserName = "Daniel"
                        });
                });

            modelBuilder.Entity("PruebaChatMVC.Models.UserChat", b =>
                {
                    b.Property<Guid>("idUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idChat")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idUser");

                    b.ToTable("UsuarioChat");
                });

            modelBuilder.Entity("PruebaChatMVC.Models.MessageSended", b =>
                {
                    b.HasOne("PruebaChatMVC.Models.User", "relReciver_User")
                        .WithMany("relUser_Reciber")
                        .HasForeignKey("Reciber")
                        .HasConstraintName("Relacion_Usuario_Receptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PruebaChatMVC.Models.User", "relSender_User")
                        .WithMany("relUser_Sender")
                        .HasForeignKey("Sender")
                        .HasConstraintName("Relacion_Usuario_Emisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("relReciver_User");

                    b.Navigation("relSender_User");
                });

            modelBuilder.Entity("PruebaChatMVC.Models.UserChat", b =>
                {
                    b.HasOne("PruebaChatMVC.Models.User", "relChat_User")
                        .WithOne("relChat_User")
                        .HasForeignKey("PruebaChatMVC.Models.UserChat", "idUser")
                        .HasConstraintName("Relacion_Usuario_Chat")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("relChat_User");
                });

            modelBuilder.Entity("PruebaChatMVC.Models.User", b =>
                {
                    b.Navigation("relChat_User");

                    b.Navigation("relUser_Reciber");

                    b.Navigation("relUser_Sender");
                });
#pragma warning restore 612, 618
        }
    }
}
