// <auto-generated />
using System;
using LibreriaChatMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaChatMVC.Migrations
{
    [DbContext(typeof(PruebaChatMVContext))]
    [Migration("20260510072354_first_migration")]
    partial class first_migration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaDeExpulsion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Integrantes");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatBase", b =>
                {
                    b.Property<Guid>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdChat");

                    b.ToTable("ChatBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.EstadoDeConexion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sumary")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosDeConexion");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaConextion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Estatuses");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Mensajes", b =>
                {
                    b.Property<Guid>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEmisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("IdMensaje");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdEmisor");

                    b.ToTable("Mensajes");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sumary")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Estatus")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.HasBaseType("LibreriaChatMVC.Models.ChatBase");

                    b.Property<int>("IdIntegrantes")
                        .HasColumnType("int");

                    b.HasIndex("IdIntegrantes");

                    b.ToTable("ChatsGrupales");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatIndividual", b =>
                {
                    b.HasBaseType("LibreriaChatMVC.Models.ChatBase");

                    b.Property<Guid>("Emisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Receptor")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Emisor");

                    b.HasIndex("Receptor");

                    b.ToTable("ChatsIndividuales");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Integrantes_Usuario")
                        .WithMany("Rel_Usuario_Integrantes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Integrantes_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.EstadoDeConexion", "Rel_Estatus_Estado")
                        .WithMany("Rel_Estado_Estatus")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Estatus_Estado");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Mensajes", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatBase", "Rel_Mensaje_Chat")
                        .WithMany("Rel_Mensajes_Chat")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Mensaje_Usuario")
                        .WithMany("Rel_Usuario_Mensajes")
                        .HasForeignKey("IdEmisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Mensaje_Chat");

                    b.Navigation("Rel_Mensaje_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Estatus", "Rel_Usuario_Estatus")
                        .WithOne("Rel_Estatus_Usuario")
                        .HasForeignKey("LibreriaChatMVC.Models.Usuario", "Estatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Roles", "Rel_Usuario_Rol")
                        .WithMany("Rel_Roles_Usuarios")
                        .HasForeignKey("Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Usuario_Estatus");

                    b.Navigation("Rel_Usuario_Rol");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatBase", null)
                        .WithOne()
                        .HasForeignKey("LibreriaChatMVC.Models.ChatGrupal", "IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.CatalogoIntegrantes", "Rel_Chats_Integrantes")
                        .WithMany("Rel_Integrantes_Chat")
                        .HasForeignKey("IdIntegrantes")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Chats_Integrantes");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatIndividual", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Emisor_Chat")
                        .WithMany("Rel_Usuario_ChatIniciados")
                        .HasForeignKey("Emisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.ChatBase", null)
                        .WithOne()
                        .HasForeignKey("LibreriaChatMVC.Models.ChatIndividual", "IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Receptor_Chat")
                        .WithMany("Rel_Usuario_ChatRecibidos")
                        .HasForeignKey("Receptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rel_Emisor_Chat");

                    b.Navigation("Rel_Receptor_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.Navigation("Rel_Integrantes_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatBase", b =>
                {
                    b.Navigation("Rel_Mensajes_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.EstadoDeConexion", b =>
                {
                    b.Navigation("Rel_Estado_Estatus");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.Navigation("Rel_Estatus_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Roles", b =>
                {
                    b.Navigation("Rel_Roles_Usuarios");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.Navigation("Rel_Usuario_ChatIniciados");

                    b.Navigation("Rel_Usuario_ChatRecibidos");

                    b.Navigation("Rel_Usuario_Integrantes");

                    b.Navigation("Rel_Usuario_Mensajes");
                });
#pragma warning restore 612, 618
        }
    }
}
