// <auto-generated />
using System;
using LibreriaChatMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaChatMVC.Migrations
{
    [DbContext(typeof(PruebaChatMVContext))]
    [Migration("20260510221015_Agregamos seeders, hacemos algunos cambios")]
    partial class Agregamosseedershacemosalgunoscambios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaDeExpulsion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Integrantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaDeIngreso = new DateTime(2026, 5, 10, 16, 10, 14, 749, DateTimeKind.Local).AddTicks(4626),
                            IdChat = new Guid("ceb6abe7-9f22-4360-9a86-f0df2eef2bfc"),
                            IdUsuario = new Guid("69f3eb14-11a6-4d74-b8c7-e2e4e9a09850")
                        },
                        new
                        {
                            Id = 2,
                            FechaDeIngreso = new DateTime(2026, 5, 10, 16, 10, 14, 749, DateTimeKind.Local).AddTicks(5203),
                            IdChat = new Guid("ceb6abe7-9f22-4360-9a86-f0df2eef2bfc"),
                            IdUsuario = new Guid("6c2c9cd7-821b-474a-86b4-252a5ad95943")
                        },
                        new
                        {
                            Id = 3,
                            FechaDeIngreso = new DateTime(2026, 5, 10, 16, 10, 14, 749, DateTimeKind.Local).AddTicks(5267),
                            IdChat = new Guid("ceb6abe7-9f22-4360-9a86-f0df2eef2bfc"),
                            IdUsuario = new Guid("db610712-17f9-40a6-b734-e3dd4bb20e1c")
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatBase", b =>
                {
                    b.Property<Guid>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdChat");

                    b.ToTable("ChatBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.EstadoDeConexion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sumary")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosDeConexion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(5558),
                            Description = "USUARIO DESCONECTADO",
                            IsDeleted = false,
                            Sumary = "DESCONECTADO"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(6691),
                            Description = "USUARIO CONECTADO",
                            IsDeleted = false,
                            Sumary = "CONECTADO"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(6696),
                            Description = "USUARIO MODO NO MOLESTAR",
                            IsDeleted = false,
                            Sumary = "NO MOLESTAR"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaConextion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("Id");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Estatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdEstatus = 1,
                            UltimaConextion = new DateTime(2026, 5, 9, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(9312)
                        },
                        new
                        {
                            Id = 2,
                            IdEstatus = 1,
                            UltimaConextion = new DateTime(2026, 5, 9, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(9807)
                        },
                        new
                        {
                            Id = 3,
                            IdEstatus = 1,
                            UltimaConextion = new DateTime(2026, 5, 9, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(9816)
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Mensajes", b =>
                {
                    b.Property<Guid>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEmisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("IdMensaje");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdEmisor");

                    b.ToTable("Mensajes");

                    b.HasData(
                        new
                        {
                            IdMensaje = new Guid("9de40981-058f-4884-8ab5-51f4a8b44171"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 750, DateTimeKind.Local).AddTicks(9033),
                            IdChat = new Guid("f329fda5-6840-40df-a734-77b30c4faff6"),
                            IdEmisor = new Guid("69f3eb14-11a6-4d74-b8c7-e2e4e9a09850"),
                            IsDeleted = false,
                            Mensaje = "Respuesta del mundo :)"
                        },
                        new
                        {
                            IdMensaje = new Guid("3b77d74a-4434-4cfb-9e10-9890aada3b4c"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 751, DateTimeKind.Local).AddTicks(1380),
                            IdChat = new Guid("5fa7f8e4-c7af-4e50-b6ba-5dcd825be575"),
                            IdEmisor = new Guid("6c2c9cd7-821b-474a-86b4-252a5ad95943"),
                            IsDeleted = false,
                            Mensaje = "Hola mundo"
                        },
                        new
                        {
                            IdMensaje = new Guid("b0da23d0-ddb1-4727-b032-989943d5b8eb"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 751, DateTimeKind.Local).AddTicks(1565),
                            IdChat = new Guid("ceb6abe7-9f22-4360-9a86-f0df2eef2bfc"),
                            IdEmisor = new Guid("69f3eb14-11a6-4d74-b8c7-e2e4e9a09850"),
                            IsDeleted = false,
                            Mensaje = "Hola a todos"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sumary")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 745, DateTimeKind.Local).AddTicks(6502),
                            Description = "Usuario administrador",
                            IsDeleted = false,
                            Sumary = "ADMIN"
                        },
                        new
                        {
                            ID = 2,
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(3926),
                            Description = "Usuario Desarrollador",
                            IsDeleted = false,
                            Sumary = "DEV"
                        },
                        new
                        {
                            ID = 3,
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 747, DateTimeKind.Local).AddTicks(3941),
                            Description = "Usuario normal",
                            IsDeleted = false,
                            Sumary = "USER"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Estatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Estatus")
                        .IsUnique();

                    b.HasIndex("Rol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("69f3eb14-11a6-4d74-b8c7-e2e4e9a09850"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 748, DateTimeKind.Local).AddTicks(2090),
                            Estatus = 1,
                            IsDeleted = false,
                            Password = "12345678",
                            Rol = 1,
                            UserName = "Usuario 0"
                        },
                        new
                        {
                            IdUsuario = new Guid("6c2c9cd7-821b-474a-86b4-252a5ad95943"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 748, DateTimeKind.Local).AddTicks(4821),
                            Estatus = 2,
                            IsDeleted = false,
                            Password = "12345678",
                            Rol = 2,
                            UserName = "Usuario 1"
                        },
                        new
                        {
                            IdUsuario = new Guid("db610712-17f9-40a6-b734-e3dd4bb20e1c"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 748, DateTimeKind.Local).AddTicks(4842),
                            Estatus = 3,
                            IsDeleted = false,
                            Password = "12345678",
                            Rol = 3,
                            UserName = "Usuario 2"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.HasBaseType("LibreriaChatMVC.Models.ChatBase");

                    b.ToTable("ChatsGrupales");

                    b.HasData(
                        new
                        {
                            IdChat = new Guid("ceb6abe7-9f22-4360-9a86-f0df2eef2bfc"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 748, DateTimeKind.Local).AddTicks(6552),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatIndividual", b =>
                {
                    b.HasBaseType("LibreriaChatMVC.Models.ChatBase");

                    b.Property<Guid>("Emisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Receptor")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Emisor");

                    b.HasIndex("Receptor");

                    b.ToTable("ChatsIndividuales");

                    b.HasData(
                        new
                        {
                            IdChat = new Guid("f329fda5-6840-40df-a734-77b30c4faff6"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 749, DateTimeKind.Local).AddTicks(8030),
                            IsDeleted = false,
                            Emisor = new Guid("69f3eb14-11a6-4d74-b8c7-e2e4e9a09850"),
                            Receptor = new Guid("6c2c9cd7-821b-474a-86b4-252a5ad95943")
                        },
                        new
                        {
                            IdChat = new Guid("5fa7f8e4-c7af-4e50-b6ba-5dcd825be575"),
                            CreateDate = new DateTime(2026, 5, 10, 16, 10, 14, 750, DateTimeKind.Local).AddTicks(1984),
                            IsDeleted = false,
                            Emisor = new Guid("6c2c9cd7-821b-474a-86b4-252a5ad95943"),
                            Receptor = new Guid("db610712-17f9-40a6-b734-e3dd4bb20e1c")
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatGrupal", "Rel_Integrantes_Chat")
                        .WithMany("Rel_Chats_Integrantes")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Integrantes_Usuario")
                        .WithMany("Rel_Usuario_Integrantes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Integrantes_Chat");

                    b.Navigation("Rel_Integrantes_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.EstadoDeConexion", "Rel_Estatus_Estado")
                        .WithMany("Rel_Estado_Estatus")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Estatus_Estado");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Mensajes", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatBase", "Rel_Mensaje_Chat")
                        .WithMany("Rel_Mensajes_Chat")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Mensaje_Usuario")
                        .WithMany("Rel_Usuario_Mensajes")
                        .HasForeignKey("IdEmisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Mensaje_Chat");

                    b.Navigation("Rel_Mensaje_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Estatus", "Rel_Usuario_Estatus")
                        .WithOne("Rel_Estatus_Usuario")
                        .HasForeignKey("LibreriaChatMVC.Models.Usuario", "Estatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Roles", "Rel_Usuario_Rol")
                        .WithMany("Rel_Roles_Usuarios")
                        .HasForeignKey("Rol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Usuario_Estatus");

                    b.Navigation("Rel_Usuario_Rol");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatBase", null)
                        .WithOne()
                        .HasForeignKey("LibreriaChatMVC.Models.ChatGrupal", "IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatIndividual", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Emisor_Chat")
                        .WithMany("Rel_Usuario_ChatIniciados")
                        .HasForeignKey("Emisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.ChatBase", null)
                        .WithOne()
                        .HasForeignKey("LibreriaChatMVC.Models.ChatIndividual", "IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Receptor_Chat")
                        .WithMany("Rel_Usuario_ChatRecibidos")
                        .HasForeignKey("Receptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rel_Emisor_Chat");

                    b.Navigation("Rel_Receptor_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatBase", b =>
                {
                    b.Navigation("Rel_Mensajes_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.EstadoDeConexion", b =>
                {
                    b.Navigation("Rel_Estado_Estatus");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.Navigation("Rel_Estatus_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Roles", b =>
                {
                    b.Navigation("Rel_Roles_Usuarios");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.Navigation("Rel_Usuario_ChatIniciados");

                    b.Navigation("Rel_Usuario_ChatRecibidos");

                    b.Navigation("Rel_Usuario_Integrantes");

                    b.Navigation("Rel_Usuario_Mensajes");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.Navigation("Rel_Chats_Integrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
