// <auto-generated />
using System;
using LibreriaChatMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaChatMVC.Migrations
{
    [DbContext(typeof(PruebaChatMVContext))]
    partial class PruebaChatMVContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("FechaDeExpulsion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaDeIngreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Integrantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FechaDeIngreso = new DateTime(2026, 6, 27, 22, 46, 6, 569, DateTimeKind.Local).AddTicks(966),
                            IdChat = new Guid("ceb37a51-6344-4a63-9e2d-9faadd2dc67e"),
                            IdUsuario = new Guid("4c95c11f-5604-40c1-827a-a49467a683f2")
                        },
                        new
                        {
                            Id = 2,
                            FechaDeIngreso = new DateTime(2026, 6, 27, 22, 46, 6, 569, DateTimeKind.Local).AddTicks(1586),
                            IdChat = new Guid("ceb37a51-6344-4a63-9e2d-9faadd2dc67e"),
                            IdUsuario = new Guid("cff3ee11-b516-4bcb-b98e-47465d5cb7cd")
                        },
                        new
                        {
                            Id = 3,
                            FechaDeIngreso = new DateTime(2026, 6, 27, 22, 46, 6, 569, DateTimeKind.Local).AddTicks(1729),
                            IdChat = new Guid("ceb37a51-6344-4a63-9e2d-9faadd2dc67e"),
                            IdUsuario = new Guid("608cf420-d67a-4b20-83d3-f49cf04e5bc6")
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatBase", b =>
                {
                    b.Property<Guid>("IdChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.HasKey("IdChat");

                    b.ToTable("ChatBase");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.EstadoDeConexion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Sumary")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("EstadosDeConexion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 565, DateTimeKind.Local).AddTicks(1116),
                            Description = "USUARIO DESCONECTADO",
                            IsDeleted = false,
                            Sumary = "DESCONECTADO"
                        },
                        new
                        {
                            Id = 2,
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 565, DateTimeKind.Local).AddTicks(2330),
                            Description = "USUARIO CONECTADO",
                            IsDeleted = false,
                            Sumary = "CONECTADO"
                        },
                        new
                        {
                            Id = 3,
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 565, DateTimeKind.Local).AddTicks(2334),
                            Description = "USUARIO MODO NO MOLESTAR",
                            IsDeleted = false,
                            Sumary = "NO MOLESTAR"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("IdEstatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UltimaConextion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEstatus");

                    b.ToTable("Estatuses");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("4c95c11f-5604-40c1-827a-a49467a683f2"),
                            IdEstatus = 1,
                            UltimaConextion = new DateTime(2026, 6, 26, 22, 46, 6, 567, DateTimeKind.Local).AddTicks(9616)
                        },
                        new
                        {
                            IdUsuario = new Guid("cff3ee11-b516-4bcb-b98e-47465d5cb7cd"),
                            IdEstatus = 1,
                            UltimaConextion = new DateTime(2026, 6, 26, 22, 46, 6, 568, DateTimeKind.Local).AddTicks(149)
                        },
                        new
                        {
                            IdUsuario = new Guid("608cf420-d67a-4b20-83d3-f49cf04e5bc6"),
                            IdEstatus = 1,
                            UltimaConextion = new DateTime(2026, 6, 26, 22, 46, 6, 568, DateTimeKind.Local).AddTicks(158)
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Mensajes", b =>
                {
                    b.Property<Guid>("IdMensaje")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEliminado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaModificado")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("IdChat")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdEmisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.HasKey("IdMensaje");

                    b.HasIndex("IdChat");

                    b.HasIndex("IdEmisor");

                    b.ToTable("Mensajes");

                    b.HasData(
                        new
                        {
                            IdMensaje = new Guid("f2ac394c-4fb2-4c89-ae26-6efdcda91dcd"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 570, DateTimeKind.Local).AddTicks(8214),
                            IdChat = new Guid("a606e76c-1999-4307-8bb8-931f76b1e7e2"),
                            IdEmisor = new Guid("4c95c11f-5604-40c1-827a-a49467a683f2"),
                            IsDeleted = false,
                            Mensaje = "Respuesta del mundo :)"
                        },
                        new
                        {
                            IdMensaje = new Guid("1f1a31f4-309e-4b0e-a526-0d785f2bac8d"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 571, DateTimeKind.Local).AddTicks(872),
                            IdChat = new Guid("743aab55-c60a-47cb-8e1f-49b1c1cc3a37"),
                            IdEmisor = new Guid("cff3ee11-b516-4bcb-b98e-47465d5cb7cd"),
                            IsDeleted = false,
                            Mensaje = "Hola mundo"
                        },
                        new
                        {
                            IdMensaje = new Guid("0c8801e1-03a5-496a-92a7-fad6567b6ce8"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 571, DateTimeKind.Local).AddTicks(1060),
                            IdChat = new Guid("ceb37a51-6344-4a63-9e2d-9faadd2dc67e"),
                            IdEmisor = new Guid("4c95c11f-5604-40c1-827a-a49467a683f2"),
                            IsDeleted = false,
                            Mensaje = "Hola a todos"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Roles", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Sumary")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("ID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 562, DateTimeKind.Local).AddTicks(8783),
                            Description = "Usuario administrador",
                            IsDeleted = false,
                            Sumary = "ADMIN"
                        },
                        new
                        {
                            ID = 2,
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 564, DateTimeKind.Local).AddTicks(9379),
                            Description = "Usuario Desarrollador",
                            IsDeleted = false,
                            Sumary = "DEV"
                        },
                        new
                        {
                            ID = 3,
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 564, DateTimeKind.Local).AddTicks(9396),
                            Description = "Usuario normal",
                            IsDeleted = false,
                            Sumary = "USER"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.Property<Guid>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Rol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = new Guid("4c95c11f-5604-40c1-827a-a49467a683f2"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 567, DateTimeKind.Local).AddTicks(848),
                            IsDeleted = false,
                            Password = "12345678",
                            Rol = 1,
                            UserName = "Usuario 0"
                        },
                        new
                        {
                            IdUsuario = new Guid("cff3ee11-b516-4bcb-b98e-47465d5cb7cd"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 567, DateTimeKind.Local).AddTicks(2754),
                            IsDeleted = false,
                            Password = "12345678",
                            Rol = 2,
                            UserName = "Usuario 1"
                        },
                        new
                        {
                            IdUsuario = new Guid("608cf420-d67a-4b20-83d3-f49cf04e5bc6"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 567, DateTimeKind.Local).AddTicks(2774),
                            IsDeleted = false,
                            Password = "12345678",
                            Rol = 3,
                            UserName = "Usuario 2"
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.HasBaseType("LibreriaChatMVC.Models.ChatBase");

                    b.ToTable("ChatsGrupales");

                    b.HasData(
                        new
                        {
                            IdChat = new Guid("ceb37a51-6344-4a63-9e2d-9faadd2dc67e"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 568, DateTimeKind.Local).AddTicks(1984),
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatIndividual", b =>
                {
                    b.HasBaseType("LibreriaChatMVC.Models.ChatBase");

                    b.Property<Guid>("Emisor")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Receptor")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("Emisor");

                    b.HasIndex("Receptor");

                    b.ToTable("ChatsIndividuales");

                    b.HasData(
                        new
                        {
                            IdChat = new Guid("a606e76c-1999-4307-8bb8-931f76b1e7e2"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 569, DateTimeKind.Local).AddTicks(5006),
                            IsDeleted = false,
                            Emisor = new Guid("4c95c11f-5604-40c1-827a-a49467a683f2"),
                            Receptor = new Guid("cff3ee11-b516-4bcb-b98e-47465d5cb7cd")
                        },
                        new
                        {
                            IdChat = new Guid("743aab55-c60a-47cb-8e1f-49b1c1cc3a37"),
                            CreateDate = new DateTime(2026, 6, 27, 22, 46, 6, 569, DateTimeKind.Local).AddTicks(9514),
                            IsDeleted = false,
                            Emisor = new Guid("cff3ee11-b516-4bcb-b98e-47465d5cb7cd"),
                            Receptor = new Guid("608cf420-d67a-4b20-83d3-f49cf04e5bc6")
                        });
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.CatalogoIntegrantes", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatGrupal", "Rel_Integrantes_Chat")
                        .WithMany("Rel_Chats_Integrantes")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Integrantes_Usuario")
                        .WithMany("Rel_Usuario_Integrantes")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Integrantes_Chat");

                    b.Navigation("Rel_Integrantes_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Estatus", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.EstadoDeConexion", "Rel_Estatus_Estado")
                        .WithMany("Rel_Estado_Estatus")
                        .HasForeignKey("IdEstatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Estatus_Usuario")
                        .WithOne("Rel_Usuario_Estatus")
                        .HasForeignKey("LibreriaChatMVC.Models.Estatus", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Estatus_Estado");

                    b.Navigation("Rel_Estatus_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Mensajes", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatBase", "Rel_Mensaje_Chat")
                        .WithMany("Rel_Mensajes_Chat")
                        .HasForeignKey("IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Mensaje_Usuario")
                        .WithMany("Rel_Usuario_Mensajes")
                        .HasForeignKey("IdEmisor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rel_Mensaje_Chat");

                    b.Navigation("Rel_Mensaje_Usuario");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Roles", "Rel_Usuario_Rol")
                        .WithMany("Rel_Roles_Usuarios")
                        .HasForeignKey("Rol")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Rel_Usuario_Rol");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.ChatBase", null)
                        .WithOne()
                        .HasForeignKey("LibreriaChatMVC.Models.ChatGrupal", "IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatIndividual", b =>
                {
                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Emisor_Chat")
                        .WithMany("Rel_Usuario_ChatIniciados")
                        .HasForeignKey("Emisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.ChatBase", null)
                        .WithOne()
                        .HasForeignKey("LibreriaChatMVC.Models.ChatIndividual", "IdChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibreriaChatMVC.Models.Usuario", "Rel_Receptor_Chat")
                        .WithMany("Rel_Usuario_ChatRecibidos")
                        .HasForeignKey("Receptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rel_Emisor_Chat");

                    b.Navigation("Rel_Receptor_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatBase", b =>
                {
                    b.Navigation("Rel_Mensajes_Chat");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.EstadoDeConexion", b =>
                {
                    b.Navigation("Rel_Estado_Estatus");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Roles", b =>
                {
                    b.Navigation("Rel_Roles_Usuarios");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.Usuario", b =>
                {
                    b.Navigation("Rel_Usuario_ChatIniciados");

                    b.Navigation("Rel_Usuario_ChatRecibidos");

                    b.Navigation("Rel_Usuario_Estatus")
                        .IsRequired();

                    b.Navigation("Rel_Usuario_Integrantes");

                    b.Navigation("Rel_Usuario_Mensajes");
                });

            modelBuilder.Entity("LibreriaChatMVC.Models.ChatGrupal", b =>
                {
                    b.Navigation("Rel_Chats_Integrantes");
                });
#pragma warning restore 612, 618
        }
    }
}
